name: Testing toolkit
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print debug messages
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
