name: Testing toolkit
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print debug messages
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::notice file={name},line={line},endLine={endLine},title={title}::{message}"
