name: Upload and Download Artifacts
on: push
jobs:
  Upload-Artifacts:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.dummy.outputs.name }}
    steps:
      - name: create dummy files
        id: dummy
        run: |
          mkdir dist
          cd dist
          touch file1 file2
          echo "name=hello Venkat" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-upload
          path: dist
  Download-Artifacts:
    runs-on: ubuntu-latest
    needs: Upload-Artifacts
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-upload
      - name: display content
        run: ls
      - name: read output
        run: echo "output value is ${{ needs.Upload-Artifacts.outputs.output1 }}"
        
          
