name: First_Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print first message
        run: echo "Hello!!"
      - name: Print Last message
        run: echo "Bye!!"
