name: Using action
on: push
jobs:
  use_actons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Display content
        run: ls -la
      - name: read content
        run: cat README.md
