name: Conditional Workflow Test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        id: test
        run: echos "Hello"
      - name: Test result
        if: failure() && steps.test.outcome == 'failure'
        run: echo "Test is success"
