name: Conditional Workflow Test
on: push
jobs:
  Test:
    strategy:
      matrix:
        runners: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Print Hello
        id: test
        run: echos "Hello"
      - name: Test result
        if: failure() && steps.test.outcome == 'failure'
        run: echo "Test is success"
