name: Conditional Workflow Test
on: push
jobs:
  Test:
    strategy:
      matrix:
        runners: [ubuntu-latest]
        include:
          - runners: windows-latest
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Print Hello
        id: test
        run: echo "Hello"
      - name: Test result
        run: echo "Test is success"
