name: Testing Outputs
on: push
jobs:
  Test:
    strategy:
      matrix:
        runners: [ubuntu-latest]
    outputs:
      outcome: ${{ steps.result.outputs.name }}
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Export output
        id: result
        run: echo "name=Hello" >> $GITHUB_OUTPUT
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read output
        run: echo "The output is ${{ needs.Test.outputs.outcome }}"
      - name: calling cutom action
        id: result
        uses: ./.github/actions/customworkflows
        with:
          name: second
      - name: Print output
        run: echo "Output is ${{ steps.result.outputs.name }}
