name: resuable workflow
on: 
  workflow_call:
    inputs:
      name:
        required: false
        default: test
        description: passing value
        type: string
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print 
        run: echo "Hi this is ${{ inputs.name }} resuable workflow"
    
